apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingjavierpinilla/feature-flag-argocd
    targetRevision: HEAD
    path: blue
  destination:
    server: https://kubernetes.default.svc
    namespace: flag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true