apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/ingjavierpinilla/feature-flag-argocd
    targetRevision: HEAD
    directory:
      exclude: '{config.json,env-usw2/*}'
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true