apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  namespace: flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: blue
  template:
    metadata:
      labels:
        app: my-app
        version: blue
    spec:
      containers:
      - name: my-app
        image: jmpinillag/color-test:0.0.2
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: configmap-blue
#k port-forward svc/argocd-server -n argocd 8080:443
#k rollout restart deployment my-app-blue   
#k get secret argocd-initial-admin-secret -n argocd -o yaml